Fix race in Cases.210 Clickhouse.001
Clickhouse test sometimes fails with an error:
ConnectionError: HTTPConnectionPool(host='localhost', port=18123): Max retries exceeded with url: /?default_format=JSONEachRow (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f40ad96fdd0>: Failed to establish a new connection: [Errno 111] Connection refused',))

Fix this by waiting for TCP port instead pid file.